name: "Coverage Report for lcov format with monorepo context support"
description: "Comments a pull request with code coverage"
author: "Forked from: GY Noh with changes by @stareintothebeard"
branding:
  icon: "check-square"
  color: "green"
inputs:
  github-token:
    description: "secrets.GITHUB_TOKEN"
    required: true
  package-name:
    description: "Package or service name within monorepo"
    required: true
  lcov-path:
    description: "Relative path of coverage/lcov.info"
    required: false
    default: 'coverage/lcov.info'
runs:
  using: "node12"
  main: "dist/index.js"
